name: WaterHomes
description: A simple home plugin for your server!
version: ${project.version}
authors: [ WatermanMC, Runkang10 ]
website: https://github.com/WatermanMC/WaterHomes
main: com.github.WatermanMC.WaterHomes.WaterHomes
api-version: "1.21"

commands:
  home:
    description: Teleport to your home
    usage: /home <home>
    permission: waterhomes.home
  sethome:
    description: Set a home
    usage: /sethome <name>
    permission: waterhomes.sethome
  homelist:
    description: See the list of your homes
    usage: /homelist
    permission: waterhomes.homelist
  waterhomes:
    description: Reload and see the information of the plugin
    usage: /waterhomes <reload|info>
    permission: waterhomes.admin

permissions:
  waterhomes.home:
    description: Teleport to your home
    default: true
  waterhomes.sethome:
    description: Set a home
    default: true
  waterhomes.sethome.<rank>:
    description: Set a multiple homes but limited
    default: false
  waterhomes.sethome.unlimited:
    description: Set a unlimited homes
    default: false
  waterhomes.homelist:
    description: See the list of your homes
    default: false
  waterhomes.bannedwords.bypass:
    description: Bypass banned words
    default: op
  waterhomes.unsafeblocks.bypass:
    description: Bypass unsafe blocks
    default: op
  waterhomes.tpdelay.bypass:
    description: Bypass Teleport delay
    default: op
  waterhomes.cooldown.bypass:
    description: Bypass Teleport cooldown
    default: op
  waterhomes.admin:
    decription: Reload and see the information of the plugin
    default: op